name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: AWS

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy through SSM
        run: |
          COMMAND_ID=$(aws ssm send-command \
            --instance-ids i-00f0422fd20ecc5dd \
            --document-name "AWS-RunShellScript" \
            --comment "Finansystem Deploy" \
            --timeout-seconds 600 \
            --parameters 'commands=[
              "sudo bash -c '\''cd /home/ubuntu/finansystem && git fetch origin main && git reset --hard origin/main && docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build && docker image prune -af'\''"
            ]' \
            --query "Command.CommandId" \
            --output text)

          echo "Command ID: $COMMAND_ID"

          aws ssm wait command-executed \
            --command-id $COMMAND_ID \
            --instance-id i-00f0422fd20ecc5dd \
            --cli-read-timeout 600 \
            --cli-connect-timeout 600

          aws ssm get-command-invocation \
            --command-id $COMMAND_ID \
            --instance-id i-00f0422fd20ecc5dd