name: Deploy to AWS

'on':
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: AWS 
    steps:
      - name: Deploy on EC2
        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          debug: true 

          script: |
            cd ~/finansystem
            git pull
            docker compose up -d --build